### ISSUE TITLE
Raspotify on the same raspberry

### ISSUE THREAD

**Issue by abjeroen** [poblouin/homebridge-spotify-speaker#15]
Hi, I've set things up and the configuration is working. I finds the ID of the spotify on my macbook and I can control it. 

I want it to control raspotify like you're doing. Raspotify is installed and working, but I can't get the spotify ID. When I reboot the raspberry, it doesn't show an ID for the raspotify client. Could this be the case because they are both on the same pi and raspotify maybe  isn't completely started yet? 

Is there another way to get the ID or scan for devices later after restart?

Edit: my macbook's spotify does see the raspotify client and I can stream towards it. I don't unserstand why this plugin doesn't show it..

**Comment by poblouin** [comment]
Hi @abjeroen, I just want to apologize to have never answered your question. I had to make a fix on the plugin yesterday and I saw that I had 2 questions, but I never received the notification for those.

Seems like you got everything working now, do not hesitate if you have other questions, I should see the notifications now 😅
