### ISSUE TITLE
Make playlist optional

### ISSUE THREAD

**Issue by m-ruhl** [poblouin/homebridge-spotify-speaker#18]
Hello,

I want to use this plugin with a slightly different use-case. I just want to have my Spotify Speaker exposed to HomeKit, which indicates if it's playing something and able to play/pause.

Therefore I don't want to specify a specific playlist to play.
If I just configure this plugin without a playlist, it's exposed in HomeKit, but the status is always off, because of this early return here:
https://github.com/poblouin/homebridge-spotify-speaker/blob/8315f62a6b427c9adad6d7701e5fd255ea79d042/src/spotify-speaker-accessory.ts#L117

For my use case I just removed this check and can use it without any problems.

It would be great if the plugin supports this out of the box :)

**Comment by poblouin** [comment]
Hey @m-ruhl! Yeah sure, that could be optional, I didn't think about it since that is not my use case, but that makes sense. I'll open a PR soon and deploy version 1.2.0 with that.

**Comment by poblouin** [comment]
I'm deplying #19, let me know if that works for you.

**Comment by m-ruhl** [comment]
Thanks @poblouin works like a charm 👍
