### ISSUE TITLE
code is not accepted

### ISSUE THREAD

**Issue by abjeroen** [poblouin/homebridge-spotify-speaker#20]
Hi @poblouin , 

Me again. I've got a fresh homebridge setup, latest version and the latest version of your app. For the life of me I cannot get the plugin connected to Spotify. I have the plugin bridged so I only have to restart the plugin, could that be an issue? I have the app registerd at spotify. I have the url added to the callback section. I do get a code back in the url. But when I paste that (and the secret+key are filled), I still get the error below.. I've tried different browsers with no luck. 

Could not authorize Spotify:

 {"body":{"error":"invalid_client"},"headers":{"date":"Tue, 03 May 2022 06:56:19 GMT","content-type":"application/json","content-length":"26","set-cookie" [...]

**Comment by poblouin** [comment]
Hi @abjeroen !

To answer the first question, I just tested using the plugin in bridge mode and it was able to connect successfully, so I think we can discard that.

I have a few questions to try to narrow down the problem.

Are you using Spotify Free or Premium?

Can you show me your JSON config please? Example here's mine where I mangled the credentials:

```
{
            "name": "HomebridgeSpotifySpeaker",
            "spotifyClientId": "974835935...",
            "spotifyClientSecret": "897238947...",
            "spotifyAuthCode": "OJ1jZ2_O6sXKk_MoT0...", <--- Here you need to paste only the code, not the full URL
            "devices": []
}

Is there any more information in the error you receive other than `invalid_client`?

**Comment by abjeroen** [comment]
Thanks for your quick response @poblouin !

My config: 
`"spotifyClientId": "7faae3xxxx",
            "spotifyClientSecret": "879xxxxxx",
            "spotifyAuthCode": "AQAqDxxxxxxx",
            "devices": [
                {
                    "deviceName": "test",
                    "deviceType": "speaker"
                }
            ],
            "platform": "HomebridgeSpotifySpeaker"Z

The error message: 
`Could not authorize Spotify:

 {"body":{"error":"invalid_client"},"headers":{"date":"Tue, 03 May 2022 12:12:03 GMT","content-type":"application/json","content-length":"26","set-cookie":["__Host-device_id=AQDEjxx;Version=1;Path=/;Max-Age=2147483647;Secure;HttpOnly;SameSite=Lax","sp_tr=false;Version=1;Domain=accounts.spotify.com;Path=/;Secure;SameSite=Lax"],"sp-trace-id":"b076xxxxx","strict-transport-security":"max-age=31536000","x-content-type-options":"nosniff","server":"envoy","via":"HTTP/2 edgeproxy, 1.1 google","alt-svc":"h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000","connection":"close"},"statusCode":400}`

**Comment by poblouin** [comment]
That would look good. And you didn't answer me, are you using Spotify Free or Premium?

That's been a long time since I had to do the auth code flow. I will bridge the plugin and try to do the flow from scratch and see if that works for me.

**Comment by abjeroen** [comment]
sorry. Yeah I'm using premium. I can stream to raspotify via the Spotify app, which requires premium as well..

**Comment by poblouin** [comment]
I just tried to remove my tokens and start the auth code flow from scratch with the plugin on a child bridge and that worked for me. I played around with the auth code also, I tried to change a few characters in it to see what would happen and I got an `invalid_grant` error. I read a bit on the `invalid_client` error and it could be a few different things. I wish we would have more information in the error..

I have a few debug logs set up on the plugin, could you maybe enable the debug mode in Homebridge and see if there are more information?

On which version of node your Homebridge instance is running? I am running on node 16.15.0 (not sure that would matter honestly, but we never know)

Have you tried running the plugin unbridged to do the initial setup?

Double check the client ID and client secret maybe? Or you could try to create a new app in your Spotify Developer Dashboard.

If nothing works, I'm happy to make a video call to try to solve the issue. It's hard to help when I can't reproduce the issue, but I think we can figure that out.

**Comment by poblouin** [comment]
Another thing that can be tried is to use curl to make the auth code grant, obtain the access token and try to call the Spotify API using curl. If it works using curl and not the plugin something would be wrong with the plugin. If curl is not working something is definitely wrong with the Spotify dev app.

I'm not sure how familiar you are with all of that though 😅

**Comment by abjeroen** [comment]
first off, I wanna thank you for replying quickly! That really helps to figure things out while I'm behind my pc :) 

I've tried the Spotify API via Postman and I can succesfully get a refresh_token back. I guess that's the "code" that normally lands in the url? That makes me believe things are fine at the spotify side.. could it be that the homebridge-plugin is using cached or old locally credential files or so?

**Comment by abjeroen** [comment]
in addition I tried creating a fresh new app in the spotify console. Sadly that gives the same result.

**Comment by abjeroen** [comment]
I've enabled debugging.. here's some of that output:

`
Finished initializing platform: HomebridgeSpotifySpeaker
[03/05/2022, 17:08:33] Publishing bridge accessory (name: HomebridgeSpotifySpeaker, publishInfo: {
  username: '0E:72:4A:45:D8:52',
  port: 34058,
  pincode: '***-**-***',
  category: 2,
  bind: undefined,
  mdns: undefined,
  addIdentifyingMaterial: true,
  advertiser: undefined
}).
[03/05/2022, 17:08:37] [HomebridgeSpotifySpeaker] Executed didFinishLaunching callback
[03/05/2022, 17:08:37] [HomebridgeSpotifySpeaker] Attempting to fetch tokens saved in the storage
[03/05/2022, 17:08:37] [HomebridgeSpotifySpeaker] Successfully fetched the tokens from storage, going to refresh the access token
[03/05/2022, 17:08:37] Homebridge v1.4.1 (HAP v0.10.2) (HomebridgeSpotifySpeaker) is running on port 34058.
[03/05/2022, 17:08:37] [HomebridgeSpotifySpeaker] Could not refresh access token:  { error: 'invalid_client', error_description: 'Invalid client' }
[03/05/2022, 17:08:37] [HomebridgeSpotifySpeaker] Attempting the code grant authorization flow
[03/05/2022, 17:08:37] [HomebridgeSpotifySpeaker] Could not authorize Spotify:

{"body":{"error":"invalid_client"},"headers":{"date":"Tue, 03 May 2022 15:08:37 GMT", [... posted already bits ..]

[03/05/2022, 17:08:37] [HomebridgeSpotifySpeaker] We could not fetch the Spotify tokens nor authenticate using the code grant flow.
        Please redo the manual login step, provide the new auth code in the config then try again.
`
I am running node 16.14.0, npm 8.5.1 and homebridge 1.4.1

**Comment by abjeroen** [comment]
might it have something to do with the callback url? I tried a callback of the default example.com or on of my own hosted websites, but both are not the place where homebridge and the plugin are installed. That would be my home ipaddress..

**Comment by poblouin** [comment]
> might it have something to do with the callback url? I tried a callback of the default [example.com](http://example.com/) or on of my own hosted websites, but both are not the place where homebridge and the plugin are installed. That would be my home ipaddress..

That doesn't matter. The callback URL could be anything really, it needs to be a website that loads. All we care about at that step is the auth grant code that is returned in the URL.

> I've tried the Spotify API via Postman and I can successfully get a refresh_token back. I guess that's the "code" that normally lands in the url? 

The auth grant code that we get in the URL and the access / refresh tokens are 2 different thing. The auth grant is used to obtain a set of tokens that we can then reuse. I'm not sure with Postman you can use the Auth Code Flow (https://developer.spotify.com/documentation/general/guides/authorization/code-flow/)


Okay so looking at the debug logs everything seems to be running normally. It first tries the tokens from the storage and fails then try the auth grant code flow and fails too. What I don't understand is the `invalid_client` error, I'm very confused by that. If the access token is invalid and it's not possible to refresh it, it should be a different error either a 401 `unauthorized` or 403 `forbidden`. Same with the auth code grant, if the code is invalid you should see `invalid_grant` like I did.

So yeah, considering all of that, that makes me wonder if the plugin is having the wrong version of the configuration maybe? But if we suppose so, I still don't see why it would return an `invalid_client`. Unless you created a Spotify Dev App in the past, used it the authenticate the plugin, deleted it from the dashboard and then the plugin would still be using that client ID which would not exist anymore? Other than that, I don't get why we have this error 🤔.

On my side though, I don't observe any caching for the configuration. If I change the config, the client ID (I change one character), I restart the plugin then I have an `invalid_client` error. Then I revert the change, restart the plugin and it's able to login again. The only cache that the plugin is using is for the access and refresh tokens. Those are stored on disk, at the root of your homebridge instance you have a file in `persist/.homebridge-spotify-speaker`. The accessories (speakers) are also cached, but this is handled by homebridge itself, not the plugin.

One thing I can offer you, is try using your client ID / secret on my Homebridge and see what happens. You can send me that over a secure channel and I can try on my side. After that you can change the secret and I won't have access to your app (but anyway don't worry, I won't use it).
